"""
WebGuard RF - Reports API
"""

from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse, PlainTextResponse, FileResponse
from pydantic import BaseModel
import markdown as md_lib

from ..core.config import settings
from ..core.deps import get_current_user
from ..services.job_store import get_job

router = APIRouter()
REPORTS_DIR = Path(settings.DATA_DIR) / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


class ExportRequest(BaseModel):
    job_id: str
    format: str = "html"


def _render_html_report(metrics: dict) -> str:
    test = metrics.get("test", {})
    train = metrics.get("train", {})
    val = metrics.get("validation", {})
    fi = metrics.get("feature_importance", {})

    rows = []
    for k, v in (test or {}).items():
        if k not in ("confusion_matrix", "per_class_metrics") and isinstance(v, (int, float)):
            rows.append(f"<tr><td>{k}</td><td>{v:.4f}</td></tr>")

    fi_rows = ""
    if fi:
        top = sorted(fi.items(), key=lambda x: -x[1])[:15]
        for name, imp in top:
            fi_rows += f"<tr><td>{name}</td><td>{imp:.4f}</td></tr>"

    return f"""<!DOCTYPE html>
<html>
<head><title>WebGuard RF Report</title>
<style>
body{{font-family:sans-serif;max-width:800px;margin:2rem auto;padding:1rem;background:#1e293b;color:#f1f5f9}}
table{{width:100%;border-collapse:collapse;margin:1rem 0}}
th,td{{padding:0.5rem;text-align:left;border:1px solid #334155}}
th{{background:#334155}}
h1{{color:#38bdf8}}
</style>
</head>
<body>
<h1>WebGuard RF - Experiment Report</h1>
<h2>Test Metrics</h2>
<table><tr><th>Metric</th><th>Value</th></tr>{"".join(rows)}</table>
<h2>Feature Importance (Top 15)</h2>
<table><tr><th>Feature</th><th>Importance</th></tr>{fi_rows}</table>
<p><small>Generated by WebGuard RF</small></p>
</body>
</html>"""


def _render_markdown_report(metrics: dict) -> str:
    test = metrics.get("test", {}) or {}
    fi = metrics.get("feature_importance", {}) or {}

    lines = ["# WebGuard RF Report", "", "## Test Metrics", ""]
    for k, v in test.items():
        if k not in ("confusion_matrix", "per_class_metrics") and isinstance(v, (int, float)):
            lines.append(f"- **{k}**: {v:.4f}")

    lines += ["", "## Feature Importance (Top 15)", ""]
    top = sorted(fi.items(), key=lambda x: -x[1])[:15]
    for name, imp in top:
        lines.append(f"- {name}: {imp:.4f}")
    return "\n".join(lines)


def _render_markdown_html_report(metrics: dict) -> str:
    md_text = _render_markdown_report(metrics)
    body_html = md_lib.markdown(md_text)
    return f"""<!DOCTYPE html>
<html>
<head><title>WebGuard RF Report (Markdown)</title>
<style>
body{{font-family:sans-serif;max-width:800px;margin:2rem auto;padding:1rem;background:#1e293b;color:#f1f5f9}}
a{{color:#38bdf8}}
code, pre{{background:#0b1220;padding:0.2rem 0.4rem;border-radius:6px}}
table{{width:100%;border-collapse:collapse;margin:1rem 0}}
th,td{{padding:0.5rem;text-align:left;border:1px solid #334155}}
th{{background:#334155}}
</style>
</head>
<body>
{body_html}
<p><small>Generated by WebGuard RF</small></p>
</body>
</html>"""


def _report_file_paths(job_id: str, fmt: str) -> tuple[Path, str]:
    if fmt == "html":
        return REPORTS_DIR / f"{job_id}_report.html", "html"
    if fmt == "markdown":
        return REPORTS_DIR / f"{job_id}_report.md", "markdown"
    raise HTTPException(400, "Format must be html or markdown")


@router.post("/export")
def export_report(req: ExportRequest, user: dict = Depends(get_current_user)):
    job = get_job(req.job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    metrics = job.get("metrics")
    if not metrics:
        raise HTTPException(400, "Job has no metrics (training may not be complete)")

    if req.format == "html":
        html = _render_html_report(metrics)
        path = REPORTS_DIR / f"{req.job_id}_report.html"
        path.write_text(html, encoding="utf-8")
        return {
            "path": str(path),
            "format": "html",
            "preview_url": f"/api/reports/{req.job_id}/preview?format=html",
        }

    if req.format == "markdown":
        md = _render_markdown_report(metrics)
        path = REPORTS_DIR / f"{req.job_id}_report.md"
        path.write_text(md, encoding="utf-8")
        return {
            "path": str(path),
            "format": "markdown",
            "preview_url": f"/api/reports/{req.job_id}/preview?format=markdown",
        }

    raise HTTPException(400, "Format must be html or markdown")


@router.get("/{job_id}/preview", response_class=HTMLResponse)
def preview_report(job_id: str, format: str = "html", user: dict = Depends(get_current_user)):
    job = get_job(job_id)
    if not job or not job.get("metrics"):
        raise HTTPException(404, "Report not found")
    metrics = job["metrics"]
    if format == "html":
        return _render_html_report(metrics)
    if format == "markdown":
        return _render_markdown_html_report(metrics)
    raise HTTPException(400, "Format must be html or markdown")


@router.get("/{job_id}/download")
def download_report(job_id: str, format: str = "html", user: dict = Depends(get_current_user)):
    path, _ = _report_file_paths(job_id, format)
    if not path.exists():
        raise HTTPException(404, "Report file not found. Export it first.")
    return FileResponse(path, filename=path.name)
