"""
WebGuard RF - Reports API
"""

from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse, PlainTextResponse
from pydantic import BaseModel

from ..core.config import settings
from ..core.deps import get_current_user
from ..services.job_store import get_job

router = APIRouter()
REPORTS_DIR = Path(settings.DATA_DIR) / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


class ExportRequest(BaseModel):
    job_id: str
    format: str = "html"


def _render_html_report(metrics: dict) -> str:
    test = metrics.get("test", {})
    train = metrics.get("train", {})
    val = metrics.get("validation", {})
    fi = metrics.get("feature_importance", {})

    rows = []
    for k, v in (test or {}).items():
        if k not in ("confusion_matrix", "per_class_metrics") and isinstance(v, (int, float)):
            rows.append(f"<tr><td>{k}</td><td>{v:.4f}</td></tr>")

    fi_rows = ""
    if fi:
        top = sorted(fi.items(), key=lambda x: -x[1])[:15]
        for name, imp in top:
            fi_rows += f"<tr><td>{name}</td><td>{imp:.4f}</td></tr>"

    return f"""<!DOCTYPE html>
<html>
<head><title>WebGuard RF Report</title>
<style>
body{{font-family:sans-serif;max-width:800px;margin:2rem auto;padding:1rem;background:#1e293b;color:#f1f5f9}}
table{{width:100%;border-collapse:collapse;margin:1rem 0}}
th,td{{padding:0.5rem;text-align:left;border:1px solid #334155}}
th{{background:#334155}}
h1{{color:#38bdf8}}
</style>
</head>
<body>
<h1>WebGuard RF - Experiment Report</h1>
<h2>Test Metrics</h2>
<table><tr><th>Metric</th><th>Value</th></tr>{"".join(rows)}</table>
<h2>Feature Importance (Top 15)</h2>
<table><tr><th>Feature</th><th>Importance</th></tr>{fi_rows}</table>
<p><small>Generated by WebGuard RF</small></p>
</body>
</html>"""


@router.post("/export")
def export_report(req: ExportRequest, user: dict = Depends(get_current_user)):
    job = get_job(req.job_id)
    if not job:
        raise HTTPException(404, "Job not found")
    metrics = job.get("metrics")
    if not metrics:
        raise HTTPException(400, "Job has no metrics (training may not be complete)")

    if req.format == "html":
        html = _render_html_report(metrics)
        path = REPORTS_DIR / f"{req.job_id}_report.html"
        path.write_text(html, encoding="utf-8")
        return {"path": str(path), "format": "html", "preview_url": f"/api/reports/{req.job_id}/preview"}

    if req.format == "markdown":
        test = metrics.get("test", {})
        md = "# WebGuard RF Report\n\n## Test Metrics\n\n"
        for k, v in (test or {}).items():
            if k not in ("confusion_matrix", "per_class_metrics") and isinstance(v, (int, float)):
                md += f"- **{k}**: {v:.4f}\n"
        path = REPORTS_DIR / f"{req.job_id}_report.md"
        path.write_text(md, encoding="utf-8")
        return {"path": str(path), "format": "markdown"}

    raise HTTPException(400, "Format must be html or markdown")


@router.get("/{job_id}/preview", response_class=HTMLResponse)
def preview_report(job_id: str, user: dict = Depends(get_current_user)):
    job = get_job(job_id)
    if not job or not job.get("metrics"):
        raise HTTPException(404, "Report not found")
    return _render_html_report(job["metrics"])
